### ISSUE TITLE
Dark Mode doesn't Invert the Color of the Mobile Bolus TextViews

### ISSUE THREAD

**Issue by NethCoder** [jwoglom/controlX2#10]
(if I could only write I title) Hello. I'm using a Samsung running Android 13 (OneUI 5.1, since it's Samsung) if that helps. In Dark Mode, every other color is a standard inverse (white -> black, and vice versa). However, the textviews on the Mobile Bolus popup have their color seemingly as #E1E3E4 / RGB(225,227,228), which makes them very hard to read.

Can they be set to straight-out black on Dark Mode, please?

![Screenshot_ControlX2](https://user-images.githubusercontent.com/52761543/235570813-a92f63be-050b-41d0-a522-ac236901b46e.jpg)

**Comment by jwoglom** [comment]
@NethCoder thanks for the report! It's not perfect yet but I made some minor improvements here. Dark mode support is a bit of a hack at the moment with a lot of manual overrides... hoping to change that eventually.

![image](https://user-images.githubusercontent.com/192620/235844255-55842004-3989-424d-9204-78b844d0b5e9.png)
