### ISSUE TITLE
Update to v7.7 Changes Pairing code Format

### ISSUE THREAD

**Issue by NethCoder** [jwoglom/controlX2#17]
Just wanted to let you know. If anyone updates their pump to work with the Dexcom G7, the software update to the pump changes the pairing code to a 6-digit code similar to 2FA codes. The code is only good for 5 minutes at a time for each G7 sensor.

![New_Pairing_Code](https://github.com/jwoglom/controlX2/assets/52761543/2c395e19-f1d4-4fc7-9861-6540f188d5b4)

**Comment by jwoglom** [comment]
This has been on my radar (once it was mentioned in the early launch announcement), but I only got access to the G7 update earlier this week and haven't updated yet. I will investigate the protocol changes and their impact on the project once I've updated my pump.

**Comment by aaroecker** [comment]
The latest Tandem update does break the connection with ControlX2.  I recently updated and am now unable to get this working again.  Hopefully an update can fix this.

**Comment by jwoglom** [comment]
I've updated my pump and good news: the core protocol has not changed. The pump reports `ApiVersionResponse[majorVersion=3,minorVersion=2]` as its API version and still appears to use the same basic auth protocol. I think the main change necessary is just to reverse engineer how the 6 character code gets translated into a 16 character code which is then sent over the wire via HMAC. I'll report in this thread when I have any further findings about this,.

**Comment by jwoglom** [comment]
@NethCoder @aaroecker the 6-digit pairing code system has been successfully reverse engineered! It ended up being much more complicated than initially expected: Tandem rewrote the entire pairing protocol using [JPAKE](https://en.wikipedia.org/wiki/Password_Authenticated_Key_Exchange_by_Juggling). Please try it out and let me know if you run into any issues.
