### ISSUE TITLE
Current status?

### ISSUE THREAD

**Issue by Miquest** [jwoglom/controlX2#9]
Hi!
What's the current status of your project?
I'm really interested in it!
Are you still developing or did you give it up?

Regards!

**Comment by jwoglom** [comment]
Hi @Miquest -- I am still working on the project, just haven't had time in recent weeks to devote to it. The current status is that we can connect to the pump, complete a bolus, and view current status from the pump, but there are some reliability issues with keeping the bluetooth connection active for the long-term without the connection dropping, and also a number of UX improvements which could be made. So, i'd classify the project as functional enough to work but not reliable or full-featured enough for 24/7 use. I hope to see that change in the right direction in the coming months, though!

**Comment by NethCoder** [comment]
Hey, just wanted to pop in a suggestion that's helped with me. It's a bit Samsung-specific, but I believe it can be adapted. When I tap for the open apps, then tap the icon of the open ControlX2 window, my Samsung gives me four options: App info, Open in split screen, Open in popup-view, and Keep open. 

I have a Z Fold (hence the split-screen), however both popup and keep open work in keeping the app in the Foreground. 

Keep open locks the app from being closed (unless Force Stopped); and, in pop-up, the app can be 'minimized' to show only as the ControlX2 icon in a circle.

![Keep Open](https://user-images.githubusercontent.com/52761543/235573204-ca1a9a13-6b3f-4004-9d98-afe952b25365.jpg)
![Locked in Foreground](https://user-images.githubusercontent.com/52761543/235573206-0edb8db4-0b83-4c22-ab62-fdb9fe53826b.jpg)
![Minimize Button](https://user-images.githubusercontent.com/52761543/235573207-95b68dc6-8f35-4f5c-8ea2-a40043d790a7.jpg)
![ControlX2 Icon](https://user-images.githubusercontent.com/52761543/235573209-0639a3b1-0962-4211-87b3-444923ab2376.jpg)

**Comment by NethCoder** [comment]
Forgot to say (I'm a scatterbrain), thanks so much for your great work on this! It really helps me.
